workmanager/objects/Work_Item__c.object
<CustomObject>
    <description>Work Manager App Object.</description>
    <fields>
        <fullName>Assigned_To__c</fullName>
        <label>Assigned To</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Work Items</relationshipLabel>
        <relationshipName>Work_Items</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Description__c</fullName>
        <label>Description</label>
        <required>true</required>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Estimated_Date__c</fullName>
        <formula>Now()+1</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Estimated Resolution Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>New</fullName>
                    <default>true</default>
                    <label>New</label>
                </value>
                <value>
                    <fullName>Ready</fullName>
                </value>
                <value>
                    <fullName>In Progress</fullName>
                </value>
                <value>
                    <fullName>Done</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Title__c</fullName>
        <label>Title</label>
        <length>50</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Idea</fullName>
                </value>
                <value>
                    <fullName>Action</fullName>
                </value>
                <value>
                    <fullName>Fix</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Work Item</label>
    <nameField>
        <displayFormat>WI-{0000000}</displayFormat>
        <label>Work Item Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Work Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

workmanager/force-app/main/default/classes/testOverdue.cls
@isTest
private class testOverdue{
    public static String CRON_EXP = '0 0 0 20 6 ? 2019';
    @testSetup
    
    
    static void setup(){
        List<Work_Item__c> wiList = new List<Work_Item__c>();
        
        for (Integer i=0;i<10;i++) {
            wiList.add(new Work_Item__c(Title__c='WI not overdue '+i, 
                                        Description__c='Description', 
                                        Status__c='New', 
                                        Type__c='Idea', 
                                        Assigned_To__c='003L000000ybjqEIAQ', 
                                        Estimated_Date__c=date.today()+1)
                      );
        }
        for (Integer i=0;i<10;i++) {
            wiList.add(new Work_Item__c(Title__c='WI overdue today '+i, 
                                        Description__c='Description', 
                                        Status__c='New', 
                                        Type__c='Fix', 
                                        Assigned_To__c='003L000000ybjqEIAQ', 
                                        Estimated_Date__c=date.today())
                      );
        }
        for (Integer i=0;i<10;i++) {
            wiList.add(new Work_Item__c(Title__c='WI overdue past '+i, 
                                        Description__c='Description', 
                                        Status__c='New', 
                                        Type__c='Action', 
                                        Assigned_To__c='003L000000ybjqEIAQ', 
                                        Estimated_Date__c=date.today()-3)
                      );
        }
        
        insert wiList;
        
    }
    
    static testmethod void test() {        
        Test.startTest();
        String jobId = System.schedule('ScheduledApexTest', CRON_EXP, new OverdueScheduler());  
        Test.stopTest();
    }
}