workmanager/objects/Work_Item__c.object
<CustomObject>
    <description>Work Manager App Object.</description>
    <fields>
        <fullName>Assigned_To__c</fullName>
        <label>Assigned To</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Work Items</relationshipLabel>
        <relationshipName>Work_Items</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Description__c</fullName>
        <label>Description</label>
        <required>true</required>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Estimated_Date__c</fullName>
        <formula>Now()+1</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Estimated Resolution Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>New</fullName>
                    <default>true</default>
                    <label>New</label>
                </value>
                <value>
                    <fullName>Ready</fullName>
                </value>
                <value>
                    <fullName>In Progress</fullName>
                </value>
                <value>
                    <fullName>Done</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Title__c</fullName>
        <label>Title</label>
        <length>50</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Idea</fullName>
                </value>
                <value>
                    <fullName>Action</fullName>
                </value>
                <value>
                    <fullName>Fix</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Work Item</label>
    <nameField>
        <displayFormat>WI-{0000000}</displayFormat>
        <label>Work Item Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Work Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

workmanager/force-app/main/default/classes/testWorkItemPanelController.cls
@isTest
private class testWorkItemPanelController {
    
    @testSetup
    static void setup(){
        //Insert Contact
        Contact c = new Contact(LastName = 'Test Contact Name');
        insert c;
        
        //Insert Work Items
        List<Work_Item__c> wiList = new List<Work_Item__c>();
        for (Integer i=0;i<5;i++) {
            wiList.add(new Work_Item__c(Title__c='New Work Item '+i, 
                                        Description__c='Description', 
                                        Status__c='New', 
                                        Type__c='Idea', 
                                        Assigned_To__c= c.Id, 
                                        Estimated_Date__c=date.today()));
        }
        for (Integer i=0;i<5;i++) {
            wiList.add(new Work_Item__c(Title__c='Ready Work Item '+i, 
                                        Description__c='Description', 
                                        Status__c='Ready', 
                                        Type__c='Fix', 
                                        Assigned_To__c= c.Id, 
                                        Estimated_Date__c=date.today()));
        }
        for (Integer i=0;i<5;i++) {
            wiList.add(new Work_Item__c(Title__c='In Progress Work Item '+i, 
                                        Description__c='Description', 
                                        Status__c='In Progress', 
                                        Type__c='Action', 
                                        Assigned_To__c= c.Id, 
                                        Estimated_Date__c=date.today()));
        }
        for (Integer i=0;i<5;i++) {
            wiList.add(new Work_Item__c(Title__c='Done Work Item '+i, 
                                        Description__c='Description', 
                                        Status__c='Done', 
                                        Type__c='Action', 
                                        Assigned_To__c= c.Id, 
                                        Estimated_Date__c=date.today()));
        }
        insert wiList;
    }
    
    static testmethod void testPanelController() {
        
        String status = 'New';
        List<Work_Item__c> results = WorkItemPanelController.getWorkItem(status);
        
        Test.startTest();
        System.AssertEquals(5, results.size(), 'Incorrect number of records returned');
        
        for(Work_Item__c r : results){
            System.Assert((r.Status__c == status), 'Returned records do not have the required status.');
        }
        Test.stopTest(); 
    }
    static testmethod void testContactPanelController() {
        
        String status = 'Done';
        Contact con = [SELECT Id, LastName FROM Contact WHERE  LastName = : 'Test Contact Name' LIMIT 1];
        String IdCon = String.valueOf(con.Id);
        
        List<Work_Item__c> results = WorkItemPanelController.getRelatedWI(IdCon);
        
        Test.startTest();
        System.AssertEquals(15, results.size(), 'Incorrect number of records returned');
        
        for(Work_Item__c r : results){
            System.Assert((r.Status__c != status), 'Returned records do not have the required status.');
        }
        Test.stopTest(); 
    }
}